#!/bin/bash
# This file is part of MyConference.
#
# MyConference is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should find a copy of the GNU Affero General Public License in the
# root directory along with this program.

set -ue
# This script is always executed in the **root** of your repository
cd MyConference/
npm install -g gulp
npm install
chmod +x hooks/after_prepare/010_add_platform_class.js
ionic state reset
cordova platform add android
gulp build
ls platforms/android/
echo
echo "Copying final artifact to docker assets directory"
sudo rm -rf docker/assets/android-debug.apk
sudo mkdir -p docker/assets
ls
sudo cp -v platforms/android/build/outputs/apk/android-debug.apk docker/assets/my-conference.apk
cd docker/assets
ls
